name: 功能建议
description: 描述你希望改善的使用场景。
title: "[Feature] "
body:
  - type: textarea
    id: problem
    attributes:
      label: 使用场景与问题
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 期望行为
    validations:
      required: true
