/var/log/tomato-focus/*.log {
    daily
    rotate 14
    maxsize 20M
    missingok
    notifempty
    compress
    delaycompress
    create 0640 www-data adm
    sharedscripts
    postrotate
        if /usr/bin/systemctl is-active --quiet nginx.service; then
            /usr/sbin/nginx -s reopen
        fi
    endscript
}
